---
- name: Install and configure PostgreSQL
  hosts: all
  become: yes

  vars:
    postgresql_version: "14"
    postgresql_user: "myuser"
    postgresql_password: "mypassword"
    postgresql_db: "mydatabase"

  tasks:
    - name: Ensure PostgreSQL is installed with required dependencies
      apt:
        name: "postgresql-{{ postgresql_version }}"
        state: present
      tags: postgresql

    - name: Install PostgreSQL contrib (optional, useful extensions)
      apt:
        name: "postgresql-contrib-{{ postgresql_version }}"
        state: present
      tags: postgresql

    - name: Ensure PostgreSQL service is running and enabled on boot
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Create PostgreSQL user
      become_user: postgres
      postgresql_user:
        name: "{{ postgresql_user }}"
        password: "{{ postgresql_password }}"
        state: present

    - name: Create a PostgreSQL database
      become_user: postgres
      postgresql_db:
        name: "{{ postgresql_db }}"
        owner: "{{ postgresql_user }}"
        state: present

    - name: Configure PostgreSQL to allow remote connections
      lineinfile:
        path: /etc/postgresql/{{ postgresql_version }}/main/postgresql.conf
        regexp: '^#?listen_addresses'
        line: "listen_addresses = '*'"
        state: present

    - name: Allow access from all IP addresses
      lineinfile:
        path: /etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf
        insertafter: '^# IPv4 local connections:'
        line: "host    all             all             0.0.0.0/0               md5"
        state: present

    - name: Restart PostgreSQL service
      service:
        name: postgresql
        state: restarted
